image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/



test:
  script:
      - Start-Process powershell -Verb runas
      -  Set-ExecutionPolicy Bypass -Scope Process -Force;iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - choco install -y python3
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -U flask-cors
      - pip install chromedriver-binary
      - cd WebScrapping
      - START /B python3 web_scrapping.py 
      - timeout 10
      - export DISPLAY=:10
      - python3 Test_AirCanada.py
      - exit(0)
