image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:


test:
  script:
      - pip3 install -r requirements.txt
      - pip3 install -U flask-cors
      - pip3 install chromedriver-binary
      - cd WebScrapping
      - python3 web_scrapping.py &
      - sleep 10
      - export DISPLAY=:10
      - python3 Test_AirCanada.py
      - exit(0)
