image: python:3.7.9-alpine
stages:

e2e:chrome:
  services:
    - selenium/standalone-chrome
  before_script:
    - pip3 install -r requirements.txt
  script:
      -pip3 install -U flask-cors
      - cd WebScrapping
      - python3 web_scrapping.py &
      - sleep 5
      - python3 Test_AirCanada.py
      - exit(0)

 