
before_script:
  - python3 -V  # Print out python version for debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install requests
  - pip3 install python-dotenv

test:
  script:
      - python3 -m unittest
