image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V
  - sudo su
  - sudo apt-get -y update
  - sudo apt-get -y install python3-pip
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt install ./google-chrome-stable_current_amd64.deb
  -  google-chrome --version

test:
  script:
      - pip3 install -r requirements.txt
      - pip3 install -U flask-cors
      - pip3 install chromedriver-binary
      - cd WebScrapping
      - python3 web_scrapping.py &
      - sleep 10
      - export DISPLAY=:10
      - python3 Test_AirCanada.py
      - exit(0)
