image: ruby:2.3

services:
- selenium/standalone-chrome:latest

variables:
  selenium_remote_url: "http://selenium__standalone-chrome:4444/wd/hub/"

cache:
  paths:
  - "./cache/ruby"

before_script:
- bundle install --path ./cache

test:
  script:
      - cd WebScrapping
      - python3 web_scrapping.py &
      - sleep 10
      - export DISPLAY=:10
      - python3 Test_AirCanada.py
      - exit(0)
