stages:
  - test

test:e2e:
  stage: test
  image: jaktestowac/python-chromedriver:3.6-xvfb

  before_script:
    - python3 -V
    - python3 -m pip install pytest
    - python3 -m pip install selenium
    - python3 -m pip install webdriver_manager
    - python3 -m pip install allure-pytest
    - pip3 install -r requirements.txt
    - pip3 install flask_cors
    - pip3 install chromedriver_binary


  script:
      - cd WebScrapping
      - python3 web_scrapping.py &
      - sleep 10
      - export DISPLAY=:10
      - python3 Test_AirCanada.py
      - exit(0)

